# This workflow will do a clean install of NodeJS 12.x on linx for every push or pull request on master and develop branches
# It will then run the tests of the app. After the tests have been run it will upload coverage reports for codacy and codecov

name: linux-14.x

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lcov.info
        path: coverage/lcov.info

