# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lcov.info
        path: coverage/lcov.info

  codacy-coverage-reporter:
    needs: build
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: lcov.info
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: f0fdcfc826ef4a0aaff49120a624fcae
          coverage-reports: lcov.info
          
  codecov-reporter:
    needs: build
    runs-on: ubuntu-latest
    name: codecov-reporter
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: lcov.info
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.infol
